server.port=8081
spring.application.name=pmp-login

# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt-BR

# MongoDB Configuration
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=mongodb://localhost:27017/pmp

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.max-block-ms=5000
spring.kafka.producer.bootstrap-servers=${spring.kafka.bootstrap-servers}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.topic.forget=forget
spring.kafka.replicas=1
spring.kafka.partitions=1
spring.kafka.admin.auto-create-topics=true

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb=INFO