server.port=${SERVER_PORT}
application.name=${APPLICATION_NAME}

# LOCALE
spring.mvc.locale-resolver=${LOCALE_RESOLVER}
spring.mvc.locale=${LOCALE}

# MongoDB Configuration
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGODB_URI}

# LOGGING / GRAYLOG
logging.level.root=INFO
logging.config=classpath:logback-spring.xml