server.port=8082
application.name=pmp

# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

# MongoDB Configuration
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/pmp

# LOGGING / GRAYLOG
logging.level.root=INFO
logging.config=classpath:logback-spring.xml
