spring.application.name=${APPLICATION_NAME}
server.port=${SERVER_PORT}

spring.cloud.gateway.routes[0].id=login-service
spring.cloud.gateway.routes[0].uri=${LOGIN_SERVICE_URI}
spring.cloud.gateway.routes[0].predicates[0]=Path=/v1/auth/**

spring.cloud.gateway.routes[1].id=users-service
spring.cloud.gateway.routes[1].uri=${LOGIN_SERVICE_URI}
spring.cloud.gateway.routes[1].predicates[0]=Path=/v1/users/**

spring.cloud.gateway.routes[2].id=pessoa-service
spring.cloud.gateway.routes[2].uri=${PESSOA_SERVICE_URI}
spring.cloud.gateway.routes[2].predicates[0]=Path=/v1/pessoas/**
