spring.application.name=pmp-consumer
server.port=8084

spring.main.allow-bean-definition-overriding=true

# Kafka Configuration
spring.kafka.bootstrap-servers=host.docker.internal:9092
spring.kafka.listener.concurrency=3
spring.kafka.topic.name=forget
spring.kafka.consumer.group-id=pmp-consumer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.bootstrap-servers=${spring.kafka.bootstrap-servers}
