spring.application.name=pmp-lambda

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.replicas=1
spring.kafka.partitions=10
spring.kafka.admin.auto-create-topics=true
spring.kafka.topic.forget=forget
spring.kafka.listener.concurrency=10
spring.kafka.producer.max-block-ms=5000
spring.kafka.producer.bootstrap-servers=${spring.kafka.bootstrap-servers}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.cloud.function.definition=forget

spring.cloud.stream.bindings.forget-in-0.destination=forget
spring.cloud.stream.bindings.forget-in-0.content-type=application/json
spring.cloud.stream.bindings.forget-in-0.group=pmp

spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.auto-create-topics=true
spring.cloud.stream.kafka.binder.consumer-properties.auto.offset.reset=earliest
